/* webkit6.c generated by valac 0.56.16, the Vala compiler
 * generated from webkit6.vala, do not modify */

#include "webkit6go.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <libnotify/notify.h>
#include <stdio.h>
#include <glib-object.h>
#include <unistd.h>
#include <webkit/webkit.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	APP_0_PROPERTY,
	APP_NUM_PROPERTIES
};
static GParamSpec* app_properties[APP_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _AppFileSaveDialogData AppFileSaveDialogData;
typedef struct _AppFileSelectDialogData AppFileSelectDialogData;
typedef struct _AppMultiFileSelectData AppMultiFileSelectData;
typedef struct _AppMultiFolderSelectData AppMultiFolderSelectData;
typedef struct _AppFolderSelectDialogData AppFolderSelectDialogData;
typedef struct _AppSelectFileAndSaveData AppSelectFileAndSaveData;
typedef struct _Block2Data Block2Data;
typedef struct _Block3Data Block3Data;
typedef struct _Block4Data Block4Data;
typedef struct _Block5Data Block5Data;

struct _AppPrivate {
	gchar* home_url;
	gchar* title;
	gint notice_n;
};

struct _Block1Data {
	int _ref_count_;
	App* self;
	gchar* uri;
};

struct _AppFileSaveDialogData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	gchar* title;
	gchar* start;
	gchar* result;
	GtkFileDialog* dlg;
	GtkFileDialog* _tmp0_;
	GtkFileDialog* _tmp1_;
	GtkFileDialog* _tmp2_;
	GFile* folder;
	GFile* _tmp3_;
	GtkFileDialog* _tmp4_;
	GFile* _tmp5_;
	GFile* res;
	GtkFileDialog* _tmp6_;
	App* _tmp7_;
	GtkWindow* _tmp8_;
	GFile* _tmp9_;
	gchar* _tmp10_;
	GError* e;
	FILE* _tmp11_;
	GError* _tmp12_;
	const gchar* _tmp13_;
	GError* _inner_error0_;
};

struct _AppFileSelectDialogData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	gchar* title;
	gchar* pattern;
	gchar* start;
	gchar* result;
	GtkFileDialog* dlg;
	GtkFileDialog* _tmp0_;
	GtkFileDialog* _tmp1_;
	GtkFileDialog* _tmp2_;
	GtkFileFilter* filter;
	GtkFileFilter* _tmp3_;
	GtkFileFilter* _tmp4_;
	GtkFileDialog* _tmp5_;
	GtkFileFilter* _tmp6_;
	GFile* folder;
	GFile* _tmp7_;
	GtkFileDialog* _tmp8_;
	GFile* _tmp9_;
	GFile* res;
	GtkFileDialog* _tmp10_;
	App* _tmp11_;
	GtkWindow* _tmp12_;
	GFile* _tmp13_;
	gchar* _tmp14_;
	GError* e;
	FILE* _tmp15_;
	GError* _tmp16_;
	const gchar* _tmp17_;
	GError* _inner_error0_;
};

struct _AppMultiFileSelectData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	gchar* title;
	gchar* pattern;
	gchar* start;
	gchar* result;
	GtkFileDialog* dlg;
	GtkFileDialog* _tmp0_;
	GtkFileDialog* _tmp1_;
	GtkFileDialog* _tmp2_;
	GtkFileFilter* filter;
	GtkFileFilter* _tmp3_;
	GtkFileFilter* _tmp4_;
	GtkFileDialog* _tmp5_;
	GtkFileFilter* _tmp6_;
	GFile* folder;
	GFile* _tmp7_;
	GtkFileDialog* _tmp8_;
	GFile* _tmp9_;
	GListModel* res;
	GtkFileDialog* _tmp10_;
	App* _tmp11_;
	GtkWindow* _tmp12_;
	GListModel* _tmp13_;
	gchar** ret;
	GListModel* _tmp14_;
	gchar** _tmp15_;
	gint ret_length1;
	gint _ret_size_;
	gint i;
	gboolean _tmp16_;
	gint _tmp17_;
	GListModel* _tmp18_;
	GFile* f;
	GListModel* _tmp19_;
	GObject* _tmp20_;
	gchar** _tmp21_;
	gint _tmp21__length1;
	GFile* _tmp22_;
	gchar* _tmp23_;
	gchar* _result_;
	gchar** _tmp24_;
	gint _tmp24__length1;
	gchar* _tmp25_;
	GError* e;
	FILE* _tmp26_;
	GError* _tmp27_;
	const gchar* _tmp28_;
	GError* _inner_error0_;
};

struct _AppMultiFolderSelectData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	gchar* title;
	gchar* start;
	gchar* result;
	GtkFileDialog* dlg;
	GtkFileDialog* _tmp0_;
	GtkFileDialog* _tmp1_;
	GtkFileDialog* _tmp2_;
	GFile* folder;
	GFile* _tmp3_;
	GtkFileDialog* _tmp4_;
	GFile* _tmp5_;
	GListModel* res;
	GtkFileDialog* _tmp6_;
	App* _tmp7_;
	GtkWindow* _tmp8_;
	GListModel* _tmp9_;
	gchar** ret;
	GListModel* _tmp10_;
	gchar** _tmp11_;
	gint ret_length1;
	gint _ret_size_;
	gint i;
	gboolean _tmp12_;
	gint _tmp13_;
	GListModel* _tmp14_;
	GFile* f;
	GListModel* _tmp15_;
	GObject* _tmp16_;
	gchar** _tmp17_;
	gint _tmp17__length1;
	GFile* _tmp18_;
	gchar* _tmp19_;
	gchar* _result_;
	gchar** _tmp20_;
	gint _tmp20__length1;
	gchar* _tmp21_;
	GError* e;
	FILE* _tmp22_;
	GError* _tmp23_;
	const gchar* _tmp24_;
	GError* _inner_error0_;
};

struct _AppFolderSelectDialogData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	gchar* title;
	gchar* start;
	gchar* result;
	GtkFileDialog* dlg;
	GtkFileDialog* _tmp0_;
	GtkFileDialog* _tmp1_;
	GtkFileDialog* _tmp2_;
	GFile* folder;
	GFile* _tmp3_;
	GtkFileDialog* _tmp4_;
	GFile* _tmp5_;
	GFile* res;
	GtkFileDialog* _tmp6_;
	App* _tmp7_;
	GtkWindow* _tmp8_;
	GFile* _tmp9_;
	gchar* _tmp10_;
	GError* e;
	FILE* _tmp11_;
	GError* _tmp12_;
	const gchar* _tmp13_;
	GError* _inner_error0_;
};

struct _AppSelectFileAndSaveData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	App* self;
	gchar* name;
	gboolean result;
	gchar* p;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	GFile* f1;
	GFile* _tmp2_;
	GFile* f2;
	const gchar* _tmp3_;
	GFile* _tmp4_;
	gboolean ret;
	GFile* _tmp5_;
	GFile* _tmp6_;
	GError* _inner_error0_;
};

struct _Block2Data {
	int _ref_count_;
	App* self;
	gchar* uri;
};

struct _Block3Data {
	int _ref_count_;
	App* self;
	WebKitDownload* download;
};

struct _Block4Data {
	int _ref_count_;
	gint w;
	gint h;
};

struct _Block5Data {
	int _ref_count_;
	WebKitWebInspector* inspector;
};

static gint App_private_offset;
static gpointer app_parent_class = NULL;
App* app_application = NULL;

static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_,
                 GApplication* app);
static void app_on_app_activate (App* self,
                          GtkApplication* app,
                          const gchar* uri);
static void ___lambda4__g_application_activate (GApplication* _sender,
                                         gpointer self);
static void app_file_save_dialog_data_free (gpointer _data);
static gboolean app_file_save_dialog_co (AppFileSaveDialogData* _data_);
static void app_file_save_dialog_ready (GObject* source_object,
                                 GAsyncResult* _res_,
                                 gpointer _user_data_);
static void app_file_select_dialog_data_free (gpointer _data);
static gboolean app_file_select_dialog_co (AppFileSelectDialogData* _data_);
static void app_file_select_dialog_ready (GObject* source_object,
                                   GAsyncResult* _res_,
                                   gpointer _user_data_);
static void app_multi_file_select_data_free (gpointer _data);
static gboolean app_multi_file_select_co (AppMultiFileSelectData* _data_);
static void app_multi_file_select_ready (GObject* source_object,
                                  GAsyncResult* _res_,
                                  gpointer _user_data_);
static void app_multi_folder_select_data_free (gpointer _data);
static gboolean app_multi_folder_select_co (AppMultiFolderSelectData* _data_);
static void app_multi_folder_select_ready (GObject* source_object,
                                    GAsyncResult* _res_,
                                    gpointer _user_data_);
static void app_folder_select_dialog_data_free (gpointer _data);
static gboolean app_folder_select_dialog_co (AppFolderSelectDialogData* _data_);
static void app_folder_select_dialog_ready (GObject* source_object,
                                     GAsyncResult* _res_,
                                     gpointer _user_data_);
static void app_select_file_and_save_data_free (gpointer _data);
static void app_select_file_and_save (App* self,
                               const gchar* name,
                               GAsyncReadyCallback _callback_,
                               gpointer _user_data_);
static gboolean app_select_file_and_save_finish (App* self,
                                          GAsyncResult* _res_);
static gboolean app_select_file_and_save_co (AppSelectFileAndSaveData* _data_);
static void app_select_file_and_save_ready (GObject* source_object,
                                     GAsyncResult* _res_,
                                     gpointer _user_data_);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda5_ (App* self,
                 WebKitDownload* download);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void __lambda6_ (Block3Data* _data3_);
static void ___lambda6__webkit_download_finished (WebKitDownload* _sender,
                                           gpointer self);
static gboolean __lambda7_ (Block3Data* _data3_,
                     const gchar* dst);
static gboolean ___lambda7__webkit_download_decide_destination (WebKitDownload* _sender,
                                                         const gchar* suggested_filename,
                                                         gpointer self);
static void ___lambda5__webkit_network_session_download_started (WebKitNetworkSession* _sender,
                                                          WebKitDownload* download,
                                                          gpointer self);
static gboolean __lambda8_ (App* self);
static gboolean ___lambda8__gtk_window_close_request (GtkWindow* _sender,
                                               gpointer self);
static gboolean __lambda9_ (Block2Data* _data2_,
                     WebKitLoadEvent e);
static gboolean ___lambda9__webkit_web_view_load_failed (WebKitWebView* _sender,
                                                  WebKitLoadEvent load_event,
                                                  const gchar* failing_uri,
                                                  GError* _error_,
                                                  gpointer self);
static gboolean __lambda10_ (App* self,
                      WebKitContextMenu* menu);
static void app_modify_menu (App* self,
                      WebKitContextMenu* menu);
static gboolean ___lambda10__webkit_web_view_context_menu (WebKitWebView* _sender,
                                                    WebKitContextMenu* context_menu,
                                                    WebKitHitTestResult* hit_test_result,
                                                    gpointer self);
static void __lambda11_ (App* self);
static void ___lambda11__g_simple_action_activate (GSimpleAction* _sender,
                                            GVariant* parameter,
                                            gpointer self);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static gboolean __lambda12_ (Block4Data* _data4_);
static gboolean ___lambda12__gsource_func (gpointer self);
static gboolean __lambda13_ (void);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
static void __lambda14_ (Block5Data* _data5_);
static void ___lambda14__webkit_web_inspector_closed (WebKitWebInspector* _sender,
                                               gpointer self);
static gboolean ___lambda13__gsource_func (gpointer self);
static void app_finalize (GObject * obj);
static GType app_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
app_get_instance_private (App* self)
{
	return G_STRUCT_MEMBER_P (self, App_private_offset);
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		App* self;
		self = _data1_->self;
		_g_free0 (_data1_->uri);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}

static void
__lambda4_ (Block1Data* _data1_,
            GApplication* app)
{
	App* self;
	GtkApplication* _tmp0_;
	self = _data1_->self;
	g_return_if_fail (app != NULL);
	_tmp0_ = self->app;
	app_on_app_activate (self, _tmp0_, _data1_->uri);
}

static void
___lambda4__g_application_activate (GApplication* _sender,
                                    gpointer self)
{
	__lambda4_ (self, _sender);
}

void
app_create (App* self,
            const gchar* id,
            const gchar* title,
            const gchar* uri)
{
	Block1Data* _data1_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	GtkApplication* _tmp2_;
	GtkApplication* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (id != NULL);
	g_return_if_fail (title != NULL);
	g_return_if_fail (uri != NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = g_strdup (uri);
	_g_free0 (_data1_->uri);
	_data1_->uri = _tmp0_;
	_tmp1_ = g_strdup (title);
	_g_free0 (self->priv->title);
	self->priv->title = _tmp1_;
	gtk_init ();
	_tmp2_ = gtk_application_new (id, G_APPLICATION_DEFAULT_FLAGS);
	_g_object_unref0 (self->app);
	self->app = _tmp2_;
	notify_init (id);
	_tmp3_ = self->app;
	g_signal_connect_data ((GApplication*) _tmp3_, "activate", (GCallback) ___lambda4__g_application_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}

gint
app_run (App* self)
{
	GtkApplication* _tmp0_;
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->app;
	result = g_application_run ((GApplication*) _tmp0_, (gint) 0, NULL);
	return result;
}

static void
app_file_save_dialog_data_free (gpointer _data)
{
	AppFileSaveDialogData* _data_;
	_data_ = _data;
	_g_free0 (_data_->title);
	_g_free0 (_data_->start);
	_g_free0 (_data_->result);
	g_slice_free (AppFileSaveDialogData, _data_);
}

void
app_file_save_dialog (const gchar* title,
                      const gchar* start,
                      GAsyncReadyCallback _callback_,
                      gpointer _user_data_)
{
	AppFileSaveDialogData* _data_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (title != NULL);
	_data_ = g_slice_new0 (AppFileSaveDialogData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, app_file_save_dialog_data_free);
	_tmp0_ = g_strdup (title);
	_g_free0 (_data_->title);
	_data_->title = _tmp0_;
	_tmp1_ = g_strdup (start);
	_g_free0 (_data_->start);
	_data_->start = _tmp1_;
	app_file_save_dialog_co (_data_);
}

gchar*
app_file_save_dialog_finish (GAsyncResult* _res_)
{
	gchar* result;
	AppFileSaveDialogData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
app_file_save_dialog_ready (GObject* source_object,
                            GAsyncResult* _res_,
                            gpointer _user_data_)
{
	AppFileSaveDialogData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	app_file_save_dialog_co (_data_);
}

static gboolean
app_file_save_dialog_co (AppFileSaveDialogData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = gtk_file_dialog_new ();
	_data_->dlg = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->dlg;
	gtk_file_dialog_set_modal (_data_->_tmp1_, TRUE);
	_data_->_tmp2_ = _data_->dlg;
	gtk_file_dialog_set_title (_data_->_tmp2_, _data_->title);
	if (_data_->start != NULL) {
		_data_->_tmp3_ = g_file_new_for_path (_data_->start);
		_data_->folder = _data_->_tmp3_;
		_data_->_tmp4_ = _data_->dlg;
		_data_->_tmp5_ = _data_->folder;
		gtk_file_dialog_set_initial_folder (_data_->_tmp4_, _data_->_tmp5_);
		_g_object_unref0 (_data_->folder);
	}
	{
		_data_->_tmp6_ = _data_->dlg;
		_data_->_tmp7_ = app_application;
		_data_->_tmp8_ = _data_->_tmp7_->win;
		_data_->_state_ = 1;
		gtk_file_dialog_save (_data_->_tmp6_, _data_->_tmp8_, NULL, app_file_save_dialog_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp9_ = gtk_file_dialog_save_finish (_data_->_tmp6_, _data_->_res_, &_data_->_inner_error0_);
		_data_->res = _data_->_tmp9_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_data_->_tmp10_ = g_file_get_path (_data_->res);
		_data_->result = _data_->_tmp10_;
		_g_object_unref0 (_data_->res);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->e = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp11_ = stderr;
		_data_->_tmp12_ = _data_->e;
		_data_->_tmp13_ = _data_->_tmp12_->message;
		fputs (_data_->_tmp13_, _data_->_tmp11_);
		_data_->result = NULL;
		_g_error_free0 (_data_->e);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally0:
	_g_object_unref0 (_data_->dlg);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
	g_clear_error (&_data_->_inner_error0_);
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
app_file_select_dialog_data_free (gpointer _data)
{
	AppFileSelectDialogData* _data_;
	_data_ = _data;
	_g_free0 (_data_->title);
	_g_free0 (_data_->pattern);
	_g_free0 (_data_->start);
	_g_free0 (_data_->result);
	g_slice_free (AppFileSelectDialogData, _data_);
}

void
app_file_select_dialog (const gchar* title,
                        const gchar* pattern,
                        const gchar* start,
                        GAsyncReadyCallback _callback_,
                        gpointer _user_data_)
{
	AppFileSelectDialogData* _data_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (title != NULL);
	_data_ = g_slice_new0 (AppFileSelectDialogData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, app_file_select_dialog_data_free);
	_tmp0_ = g_strdup (title);
	_g_free0 (_data_->title);
	_data_->title = _tmp0_;
	_tmp1_ = g_strdup (pattern);
	_g_free0 (_data_->pattern);
	_data_->pattern = _tmp1_;
	_tmp2_ = g_strdup (start);
	_g_free0 (_data_->start);
	_data_->start = _tmp2_;
	app_file_select_dialog_co (_data_);
}

gchar*
app_file_select_dialog_finish (GAsyncResult* _res_)
{
	gchar* result;
	AppFileSelectDialogData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
app_file_select_dialog_ready (GObject* source_object,
                              GAsyncResult* _res_,
                              gpointer _user_data_)
{
	AppFileSelectDialogData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	app_file_select_dialog_co (_data_);
}

static gboolean
app_file_select_dialog_co (AppFileSelectDialogData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = gtk_file_dialog_new ();
	_data_->dlg = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->dlg;
	gtk_file_dialog_set_modal (_data_->_tmp1_, TRUE);
	_data_->_tmp2_ = _data_->dlg;
	gtk_file_dialog_set_title (_data_->_tmp2_, _data_->title);
	if (_data_->pattern != NULL) {
		_data_->_tmp3_ = gtk_file_filter_new ();
		_data_->filter = _data_->_tmp3_;
		_data_->_tmp4_ = _data_->filter;
		gtk_file_filter_add_pattern (_data_->_tmp4_, _data_->pattern);
		_data_->_tmp5_ = _data_->dlg;
		_data_->_tmp6_ = _data_->filter;
		gtk_file_dialog_set_default_filter (_data_->_tmp5_, _data_->_tmp6_);
		_g_object_unref0 (_data_->filter);
	}
	if (_data_->start != NULL) {
		_data_->_tmp7_ = g_file_new_for_path (_data_->start);
		_data_->folder = _data_->_tmp7_;
		_data_->_tmp8_ = _data_->dlg;
		_data_->_tmp9_ = _data_->folder;
		gtk_file_dialog_set_initial_folder (_data_->_tmp8_, _data_->_tmp9_);
		_g_object_unref0 (_data_->folder);
	}
	{
		_data_->_tmp10_ = _data_->dlg;
		_data_->_tmp11_ = app_application;
		_data_->_tmp12_ = _data_->_tmp11_->win;
		_data_->_state_ = 1;
		gtk_file_dialog_open (_data_->_tmp10_, _data_->_tmp12_, NULL, app_file_select_dialog_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp13_ = gtk_file_dialog_open_finish (_data_->_tmp10_, _data_->_res_, &_data_->_inner_error0_);
		_data_->res = _data_->_tmp13_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_data_->_tmp14_ = g_file_get_path (_data_->res);
		_data_->result = _data_->_tmp14_;
		_g_object_unref0 (_data_->res);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->e = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp15_ = stderr;
		_data_->_tmp16_ = _data_->e;
		_data_->_tmp17_ = _data_->_tmp16_->message;
		fputs (_data_->_tmp17_, _data_->_tmp15_);
		_data_->result = NULL;
		_g_error_free0 (_data_->e);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally0:
	_g_object_unref0 (_data_->dlg);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
	g_clear_error (&_data_->_inner_error0_);
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
app_multi_file_select_data_free (gpointer _data)
{
	AppMultiFileSelectData* _data_;
	_data_ = _data;
	_g_free0 (_data_->title);
	_g_free0 (_data_->pattern);
	_g_free0 (_data_->start);
	_g_free0 (_data_->result);
	g_slice_free (AppMultiFileSelectData, _data_);
}

void
app_multi_file_select (const gchar* title,
                       const gchar* pattern,
                       const gchar* start,
                       GAsyncReadyCallback _callback_,
                       gpointer _user_data_)
{
	AppMultiFileSelectData* _data_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (title != NULL);
	_data_ = g_slice_new0 (AppMultiFileSelectData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, app_multi_file_select_data_free);
	_tmp0_ = g_strdup (title);
	_g_free0 (_data_->title);
	_data_->title = _tmp0_;
	_tmp1_ = g_strdup (pattern);
	_g_free0 (_data_->pattern);
	_data_->pattern = _tmp1_;
	_tmp2_ = g_strdup (start);
	_g_free0 (_data_->start);
	_data_->start = _tmp2_;
	app_multi_file_select_co (_data_);
}

gchar*
app_multi_file_select_finish (GAsyncResult* _res_)
{
	gchar* result;
	AppMultiFileSelectData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
app_multi_file_select_ready (GObject* source_object,
                             GAsyncResult* _res_,
                             gpointer _user_data_)
{
	AppMultiFileSelectData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	app_multi_file_select_co (_data_);
}

static gchar*
_vala_g_strjoinv (const gchar* separator,
                  gchar** str_array,
                  gint str_array_length1)
{
	gboolean _tmp0_ = FALSE;
	gchar* result;
	if (separator == NULL) {
		separator = "";
	}
	if (str_array != NULL) {
		gboolean _tmp1_ = FALSE;
		if (str_array_length1 > 0) {
			_tmp1_ = TRUE;
		} else {
			gboolean _tmp2_ = FALSE;
			if (str_array_length1 == -1) {
				const gchar* _tmp3_;
				_tmp3_ = str_array[0];
				_tmp2_ = _tmp3_ != NULL;
			} else {
				_tmp2_ = FALSE;
			}
			_tmp1_ = _tmp2_;
		}
		_tmp0_ = _tmp1_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gint i = 0;
		gsize len = 0UL;
		gint _tmp16_;
		gint _tmp17_;
		const gchar* res = NULL;
		void* _tmp18_;
		const gchar* _tmp19_ = NULL;
		const gchar* _tmp20_;
		void* ptr = NULL;
		const gchar* _tmp22_;
		void* _tmp23_;
		const gchar* _tmp33_;
		len = (gsize) 1;
		{
			gboolean _tmp4_ = FALSE;
			i = 0;
			_tmp4_ = TRUE;
			while (TRUE) {
				gboolean _tmp6_ = FALSE;
				gboolean _tmp7_ = FALSE;
				gint _tmp10_ = 0;
				const gchar* _tmp11_;
				if (!_tmp4_) {
					gint _tmp5_;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				if (str_array_length1 != -1) {
					_tmp7_ = i < str_array_length1;
				} else {
					_tmp7_ = FALSE;
				}
				if (_tmp7_) {
					_tmp6_ = TRUE;
				} else {
					gboolean _tmp8_ = FALSE;
					if (str_array_length1 == -1) {
						const gchar* _tmp9_;
						_tmp9_ = str_array[i];
						_tmp8_ = _tmp9_ != NULL;
					} else {
						_tmp8_ = FALSE;
					}
					_tmp6_ = _tmp8_;
				}
				if (!_tmp6_) {
					break;
				}
				_tmp11_ = str_array[i];
				if (_tmp11_ != NULL) {
					const gchar* _tmp12_;
					gint _tmp13_;
					gint _tmp14_;
					_tmp12_ = str_array[i];
					_tmp13_ = strlen ((const gchar*) _tmp12_);
					_tmp14_ = _tmp13_;
					_tmp10_ = _tmp14_;
				} else {
					_tmp10_ = 0;
				}
				len += (gsize) _tmp10_;
			}
		}
		if (i == 0) {
			gchar* _tmp15_;
			_tmp15_ = g_strdup ("");
			result = _tmp15_;
			return result;
		}
		str_array_length1 = i;
		_tmp16_ = strlen ((const gchar*) separator);
		_tmp17_ = _tmp16_;
		len += (gsize) (_tmp17_ * (i - 1));
		_tmp18_ = g_malloc (len);
		res = _tmp18_;
		_tmp20_ = str_array[0];
		if (_tmp20_ != NULL) {
			const gchar* _tmp21_;
			_tmp21_ = str_array[0];
			_tmp19_ = (const gchar*) _tmp21_;
		} else {
			_tmp19_ = "";
		}
		_tmp22_ = res;
		_tmp23_ = g_stpcpy ((void*) _tmp22_, _tmp19_);
		ptr = _tmp23_;
		{
			gboolean _tmp24_ = FALSE;
			i = 1;
			_tmp24_ = TRUE;
			while (TRUE) {
				void* _tmp26_;
				void* _tmp27_;
				const gchar* _tmp28_ = NULL;
				const gchar* _tmp29_;
				void* _tmp31_;
				void* _tmp32_;
				if (!_tmp24_) {
					gint _tmp25_;
					_tmp25_ = i;
					i = _tmp25_ + 1;
				}
				_tmp24_ = FALSE;
				if (!(i < str_array_length1)) {
					break;
				}
				_tmp26_ = ptr;
				_tmp27_ = g_stpcpy (_tmp26_, (const gchar*) separator);
				ptr = _tmp27_;
				_tmp29_ = str_array[i];
				if (_tmp29_ != NULL) {
					const gchar* _tmp30_;
					_tmp30_ = str_array[i];
					_tmp28_ = (const gchar*) _tmp30_;
				} else {
					_tmp28_ = "";
				}
				_tmp31_ = ptr;
				_tmp32_ = g_stpcpy (_tmp31_, _tmp28_);
				ptr = _tmp32_;
			}
		}
		_tmp33_ = res;
		res = NULL;
		result = (gchar*) _tmp33_;
		return result;
	} else {
		gchar* _tmp34_;
		_tmp34_ = g_strdup ("");
		result = _tmp34_;
		return result;
	}
}

static gboolean
app_multi_file_select_co (AppMultiFileSelectData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = gtk_file_dialog_new ();
	_data_->dlg = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->dlg;
	gtk_file_dialog_set_modal (_data_->_tmp1_, TRUE);
	_data_->_tmp2_ = _data_->dlg;
	gtk_file_dialog_set_title (_data_->_tmp2_, _data_->title);
	if (_data_->pattern != NULL) {
		_data_->_tmp3_ = gtk_file_filter_new ();
		_data_->filter = _data_->_tmp3_;
		_data_->_tmp4_ = _data_->filter;
		gtk_file_filter_add_pattern (_data_->_tmp4_, _data_->pattern);
		_data_->_tmp5_ = _data_->dlg;
		_data_->_tmp6_ = _data_->filter;
		gtk_file_dialog_set_default_filter (_data_->_tmp5_, _data_->_tmp6_);
		_g_object_unref0 (_data_->filter);
	}
	if (_data_->start != NULL) {
		_data_->_tmp7_ = g_file_new_for_path (_data_->start);
		_data_->folder = _data_->_tmp7_;
		_data_->_tmp8_ = _data_->dlg;
		_data_->_tmp9_ = _data_->folder;
		gtk_file_dialog_set_initial_folder (_data_->_tmp8_, _data_->_tmp9_);
		_g_object_unref0 (_data_->folder);
	}
	{
		_data_->_tmp10_ = _data_->dlg;
		_data_->_tmp11_ = app_application;
		_data_->_tmp12_ = _data_->_tmp11_->win;
		_data_->_state_ = 1;
		gtk_file_dialog_open_multiple (_data_->_tmp10_, _data_->_tmp12_, NULL, app_multi_file_select_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp13_ = gtk_file_dialog_open_multiple_finish (_data_->_tmp10_, _data_->_res_, &_data_->_inner_error0_);
		_data_->res = _data_->_tmp13_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_data_->_tmp14_ = _data_->res;
		_data_->_tmp15_ = g_new0 (gchar*, g_list_model_get_n_items (_data_->_tmp14_) + 1);
		_data_->ret = _data_->_tmp15_;
		_data_->ret_length1 = g_list_model_get_n_items (_data_->_tmp14_);
		_data_->_ret_size_ = _data_->ret_length1;
		{
			_data_->i = 0;
			{
				_data_->_tmp16_ = TRUE;
				while (TRUE) {
					if (!_data_->_tmp16_) {
						_data_->_tmp17_ = _data_->i;
						_data_->i = _data_->_tmp17_ + 1;
					}
					_data_->_tmp16_ = FALSE;
					_data_->_tmp18_ = _data_->res;
					if (!(((guint) _data_->i) < g_list_model_get_n_items (_data_->_tmp18_))) {
						break;
					}
					_data_->_tmp19_ = _data_->res;
					_data_->_tmp20_ = g_list_model_get_item (_data_->_tmp19_, (guint) _data_->i);
					_data_->f = G_TYPE_CHECK_INSTANCE_CAST (_data_->_tmp20_, g_file_get_type (), GFile);
					_data_->_tmp21_ = _data_->ret;
					_data_->_tmp21__length1 = _data_->ret_length1;
					_data_->_tmp22_ = _data_->f;
					_data_->_tmp23_ = g_file_get_path (_data_->_tmp22_);
					_g_free0 (_data_->_tmp21_[_data_->i]);
					_data_->_tmp21_[_data_->i] = _data_->_tmp23_;
					_g_object_unref0 (_data_->f);
				}
			}
		}
		_data_->_tmp24_ = _data_->ret;
		_data_->_tmp24__length1 = _data_->ret_length1;
		_data_->_tmp25_ = _vala_g_strjoinv (":", _data_->_tmp24_, (gint) _data_->_tmp24__length1);
		_data_->_result_ = _data_->_tmp25_;
		_data_->result = _data_->_result_;
		_data_->ret = (_vala_array_free (_data_->ret, _data_->ret_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (_data_->res);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->e = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp26_ = stderr;
		_data_->_tmp27_ = _data_->e;
		_data_->_tmp28_ = _data_->_tmp27_->message;
		fputs (_data_->_tmp28_, _data_->_tmp26_);
		_data_->result = NULL;
		_g_error_free0 (_data_->e);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally0:
	_g_object_unref0 (_data_->dlg);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
	g_clear_error (&_data_->_inner_error0_);
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
app_multi_folder_select_data_free (gpointer _data)
{
	AppMultiFolderSelectData* _data_;
	_data_ = _data;
	_g_free0 (_data_->title);
	_g_free0 (_data_->start);
	_g_free0 (_data_->result);
	g_slice_free (AppMultiFolderSelectData, _data_);
}

void
app_multi_folder_select (const gchar* title,
                         const gchar* start,
                         GAsyncReadyCallback _callback_,
                         gpointer _user_data_)
{
	AppMultiFolderSelectData* _data_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (title != NULL);
	_data_ = g_slice_new0 (AppMultiFolderSelectData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, app_multi_folder_select_data_free);
	_tmp0_ = g_strdup (title);
	_g_free0 (_data_->title);
	_data_->title = _tmp0_;
	_tmp1_ = g_strdup (start);
	_g_free0 (_data_->start);
	_data_->start = _tmp1_;
	app_multi_folder_select_co (_data_);
}

gchar*
app_multi_folder_select_finish (GAsyncResult* _res_)
{
	gchar* result;
	AppMultiFolderSelectData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
app_multi_folder_select_ready (GObject* source_object,
                               GAsyncResult* _res_,
                               gpointer _user_data_)
{
	AppMultiFolderSelectData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	app_multi_folder_select_co (_data_);
}

static gboolean
app_multi_folder_select_co (AppMultiFolderSelectData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = gtk_file_dialog_new ();
	_data_->dlg = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->dlg;
	gtk_file_dialog_set_modal (_data_->_tmp1_, TRUE);
	_data_->_tmp2_ = _data_->dlg;
	gtk_file_dialog_set_title (_data_->_tmp2_, _data_->title);
	if (_data_->start != NULL) {
		_data_->_tmp3_ = g_file_new_for_path (_data_->start);
		_data_->folder = _data_->_tmp3_;
		_data_->_tmp4_ = _data_->dlg;
		_data_->_tmp5_ = _data_->folder;
		gtk_file_dialog_set_initial_folder (_data_->_tmp4_, _data_->_tmp5_);
		_g_object_unref0 (_data_->folder);
	}
	{
		_data_->_tmp6_ = _data_->dlg;
		_data_->_tmp7_ = app_application;
		_data_->_tmp8_ = _data_->_tmp7_->win;
		_data_->_state_ = 1;
		gtk_file_dialog_select_multiple_folders (_data_->_tmp6_, _data_->_tmp8_, NULL, app_multi_folder_select_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp9_ = gtk_file_dialog_select_multiple_folders_finish (_data_->_tmp6_, _data_->_res_, &_data_->_inner_error0_);
		_data_->res = _data_->_tmp9_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_data_->_tmp10_ = _data_->res;
		_data_->_tmp11_ = g_new0 (gchar*, g_list_model_get_n_items (_data_->_tmp10_) + 1);
		_data_->ret = _data_->_tmp11_;
		_data_->ret_length1 = g_list_model_get_n_items (_data_->_tmp10_);
		_data_->_ret_size_ = _data_->ret_length1;
		{
			_data_->i = 0;
			{
				_data_->_tmp12_ = TRUE;
				while (TRUE) {
					if (!_data_->_tmp12_) {
						_data_->_tmp13_ = _data_->i;
						_data_->i = _data_->_tmp13_ + 1;
					}
					_data_->_tmp12_ = FALSE;
					_data_->_tmp14_ = _data_->res;
					if (!(((guint) _data_->i) < g_list_model_get_n_items (_data_->_tmp14_))) {
						break;
					}
					_data_->_tmp15_ = _data_->res;
					_data_->_tmp16_ = g_list_model_get_item (_data_->_tmp15_, (guint) _data_->i);
					_data_->f = G_TYPE_CHECK_INSTANCE_CAST (_data_->_tmp16_, g_file_get_type (), GFile);
					_data_->_tmp17_ = _data_->ret;
					_data_->_tmp17__length1 = _data_->ret_length1;
					_data_->_tmp18_ = _data_->f;
					_data_->_tmp19_ = g_file_get_path (_data_->_tmp18_);
					_g_free0 (_data_->_tmp17_[_data_->i]);
					_data_->_tmp17_[_data_->i] = _data_->_tmp19_;
					_g_object_unref0 (_data_->f);
				}
			}
		}
		_data_->_tmp20_ = _data_->ret;
		_data_->_tmp20__length1 = _data_->ret_length1;
		_data_->_tmp21_ = _vala_g_strjoinv (":", _data_->_tmp20_, (gint) _data_->_tmp20__length1);
		_data_->_result_ = _data_->_tmp21_;
		_data_->result = _data_->_result_;
		_data_->ret = (_vala_array_free (_data_->ret, _data_->ret_length1, (GDestroyNotify) g_free), NULL);
		_g_object_unref0 (_data_->res);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->e = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp22_ = stderr;
		_data_->_tmp23_ = _data_->e;
		_data_->_tmp24_ = _data_->_tmp23_->message;
		fputs (_data_->_tmp24_, _data_->_tmp22_);
		_data_->result = NULL;
		_g_error_free0 (_data_->e);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally0:
	_g_object_unref0 (_data_->dlg);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
	g_clear_error (&_data_->_inner_error0_);
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
app_folder_select_dialog_data_free (gpointer _data)
{
	AppFolderSelectDialogData* _data_;
	_data_ = _data;
	_g_free0 (_data_->title);
	_g_free0 (_data_->start);
	_g_free0 (_data_->result);
	g_slice_free (AppFolderSelectDialogData, _data_);
}

void
app_folder_select_dialog (const gchar* title,
                          const gchar* start,
                          GAsyncReadyCallback _callback_,
                          gpointer _user_data_)
{
	AppFolderSelectDialogData* _data_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (title != NULL);
	_data_ = g_slice_new0 (AppFolderSelectDialogData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, app_folder_select_dialog_data_free);
	_tmp0_ = g_strdup (title);
	_g_free0 (_data_->title);
	_data_->title = _tmp0_;
	_tmp1_ = g_strdup (start);
	_g_free0 (_data_->start);
	_data_->start = _tmp1_;
	app_folder_select_dialog_co (_data_);
}

gchar*
app_folder_select_dialog_finish (GAsyncResult* _res_)
{
	gchar* result;
	AppFolderSelectDialogData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
app_folder_select_dialog_ready (GObject* source_object,
                                GAsyncResult* _res_,
                                gpointer _user_data_)
{
	AppFolderSelectDialogData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	app_folder_select_dialog_co (_data_);
}

static gboolean
app_folder_select_dialog_co (AppFolderSelectDialogData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = gtk_file_dialog_new ();
	_data_->dlg = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->dlg;
	gtk_file_dialog_set_modal (_data_->_tmp1_, TRUE);
	_data_->_tmp2_ = _data_->dlg;
	gtk_file_dialog_set_title (_data_->_tmp2_, _data_->title);
	if (_data_->start != NULL) {
		_data_->_tmp3_ = g_file_new_for_path (_data_->start);
		_data_->folder = _data_->_tmp3_;
		_data_->_tmp4_ = _data_->dlg;
		_data_->_tmp5_ = _data_->folder;
		gtk_file_dialog_set_initial_folder (_data_->_tmp4_, _data_->_tmp5_);
		_g_object_unref0 (_data_->folder);
	}
	{
		_data_->_tmp6_ = _data_->dlg;
		_data_->_tmp7_ = app_application;
		_data_->_tmp8_ = _data_->_tmp7_->win;
		_data_->_state_ = 1;
		gtk_file_dialog_select_folder (_data_->_tmp6_, _data_->_tmp8_, NULL, app_folder_select_dialog_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp9_ = gtk_file_dialog_select_folder_finish (_data_->_tmp6_, _data_->_res_, &_data_->_inner_error0_);
		_data_->res = _data_->_tmp9_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_data_->_tmp10_ = g_file_get_path (_data_->res);
		_data_->result = _data_->_tmp10_;
		_g_object_unref0 (_data_->res);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->e = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp11_ = stderr;
		_data_->_tmp12_ = _data_->e;
		_data_->_tmp13_ = _data_->_tmp12_->message;
		fputs (_data_->_tmp13_, _data_->_tmp11_);
		_data_->result = NULL;
		_g_error_free0 (_data_->e);
		_g_object_unref0 (_data_->dlg);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally0:
	_g_object_unref0 (_data_->dlg);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
	g_clear_error (&_data_->_inner_error0_);
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
app_select_file_and_save_data_free (gpointer _data)
{
	AppSelectFileAndSaveData* _data_;
	_data_ = _data;
	_g_free0 (_data_->name);
	_g_object_unref0 (_data_->self);
	g_slice_free (AppSelectFileAndSaveData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
app_select_file_and_save (App* self,
                          const gchar* name,
                          GAsyncReadyCallback _callback_,
                          gpointer _user_data_)
{
	AppSelectFileAndSaveData* _data_;
	App* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_data_ = g_slice_new0 (AppSelectFileAndSaveData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, app_select_file_and_save_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = g_strdup (name);
	_g_free0 (_data_->name);
	_data_->name = _tmp1_;
	app_select_file_and_save_co (_data_);
}

static gboolean
app_select_file_and_save_finish (App* self,
                                 GAsyncResult* _res_)
{
	gboolean result;
	AppSelectFileAndSaveData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	return result;
}

static void
app_select_file_and_save_ready (GObject* source_object,
                                GAsyncResult* _res_,
                                gpointer _user_data_)
{
	AppSelectFileAndSaveData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	app_select_file_and_save_co (_data_);
}

static gboolean
app_select_file_and_save_co (AppSelectFileAndSaveData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_state_ = 1;
	app_file_save_dialog ("保存文件(Save file)", NULL, app_select_file_and_save_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp0_ = app_file_save_dialog_finish (_data_->_res_);
	_data_->p = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->p;
	if (_data_->_tmp1_ != NULL) {
		_data_->_tmp2_ = g_file_new_for_path (_data_->name);
		_data_->f1 = _data_->_tmp2_;
		_data_->_tmp3_ = _data_->p;
		_data_->_tmp4_ = g_file_new_for_path (_data_->_tmp3_);
		_data_->f2 = _data_->_tmp4_;
		{
			_data_->_tmp5_ = _data_->f1;
			_data_->_tmp6_ = _data_->f2;
			_data_->ret = g_file_copy (_data_->_tmp5_, _data_->_tmp6_, G_FILE_COPY_OVERWRITE, NULL, NULL, NULL, &_data_->_inner_error0_);
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
				goto __catch0_g_error;
			}
			unlink (_data_->name);
			_data_->result = _data_->ret;
			_g_object_unref0 (_data_->f2);
			_g_object_unref0 (_data_->f1);
			_g_free0 (_data_->p);
			g_task_return_pointer (_data_->_async_result, _data_, NULL);
			if (_data_->_state_ != 0) {
				while (!g_task_get_completed (_data_->_async_result)) {
					g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
				}
			}
			g_object_unref (_data_->_async_result);
			return FALSE;
		}
		goto __finally0;
		__catch0_g_error:
		{
			g_clear_error (&_data_->_inner_error0_);
		}
		__finally0:
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			_g_object_unref0 (_data_->f2);
			_g_object_unref0 (_data_->f1);
			_g_free0 (_data_->p);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
			g_clear_error (&_data_->_inner_error0_);
			g_object_unref (_data_->_async_result);
			return FALSE;
		}
		_g_object_unref0 (_data_->f2);
		_g_object_unref0 (_data_->f1);
	}
	_data_->result = TRUE;
	_g_free0 (_data_->p);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		App* self;
		self = _data2_->self;
		_g_free0 (_data2_->uri);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		App* self;
		self = _data3_->self;
		_g_object_unref0 (_data3_->download);
		_g_object_unref0 (self);
		g_slice_free (Block3Data, _data3_);
	}
}

static void
__lambda6_ (Block3Data* _data3_)
{
	App* self;
	const gchar* _tmp0_;
	self = _data3_->self;
	_tmp0_ = webkit_download_get_destination (_data3_->download);
	app_select_file_and_save (self, _tmp0_, NULL, NULL);
}

static void
___lambda6__webkit_download_finished (WebKitDownload* _sender,
                                      gpointer self)
{
	__lambda6_ (self);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static gboolean
__lambda7_ (Block3Data* _data3_,
            const gchar* dst)
{
	App* self;
	gchar* dir1 = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* fname = NULL;
	gchar* _tmp2_;
	gchar* name = NULL;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	GFile* f = NULL;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GFile* _tmp9_;
	GFile* _tmp10_;
	GFile* _tmp11_;
	gchar* dst_name = NULL;
	const gchar* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	NotifyNotification* notice = NULL;
	const gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	NotifyNotification* _tmp22_;
	NotifyNotification* _tmp23_;
	gint _tmp28_;
	GError* _inner_error0_ = NULL;
	gboolean result;
	self = _data3_->self;
	g_return_val_if_fail (dst != NULL, FALSE);
	_tmp0_ = g_get_user_special_dir (G_USER_DIRECTORY_DOWNLOAD);
	_tmp1_ = g_strdup (_tmp0_);
	dir1 = _tmp1_;
	_tmp2_ = g_strdup (dst);
	fname = _tmp2_;
	_tmp3_ = fname;
	_tmp4_ = g_strdup (_tmp3_);
	name = _tmp4_;
	_tmp5_ = dir1;
	_tmp6_ = name;
	_tmp7_ = g_build_filename (_tmp5_, _tmp6_, NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_file_new_for_path (_tmp8_);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	f = _tmp10_;
	_tmp11_ = f;
	if (g_file_query_exists (_tmp11_, NULL)) {
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		_tmp12_ = dir1;
		_tmp13_ = name;
		_tmp14_ = g_build_filename (_tmp12_, _tmp13_, NULL);
		_tmp15_ = _tmp14_;
		unlink (_tmp15_);
		_g_free0 (_tmp15_);
	}
	_tmp16_ = dir1;
	_tmp17_ = name;
	_tmp18_ = g_build_filename (_tmp16_, _tmp17_, NULL);
	dst_name = _tmp18_;
	webkit_download_set_destination (_data3_->download, dst_name);
	_tmp19_ = string_to_string (dst_name);
	_tmp20_ = g_strconcat ("Save: ", _tmp19_, NULL);
	_tmp21_ = _tmp20_;
	_tmp22_ = notify_notification_new (_tmp21_, NULL, NULL);
	_tmp23_ = _tmp22_;
	_g_free0 (_tmp21_);
	notice = _tmp23_;
	{
		notify_notification_show (notice, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp24_;
		GError* _tmp25_;
		const gchar* _tmp26_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp24_ = stderr;
		_tmp25_ = e;
		_tmp26_ = _tmp25_->message;
		fputs (_tmp26_, _tmp24_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gboolean _tmp27_ = FALSE;
		_g_object_unref0 (notice);
		_g_free0 (dst_name);
		_g_object_unref0 (f);
		_g_free0 (name);
		_g_free0 (fname);
		_g_free0 (dir1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp27_;
	}
	_tmp28_ = self->priv->notice_n;
	self->priv->notice_n = _tmp28_ + 1;
	result = TRUE;
	_g_object_unref0 (notice);
	_g_free0 (dst_name);
	_g_object_unref0 (f);
	_g_free0 (name);
	_g_free0 (fname);
	_g_free0 (dir1);
	return result;
}

static gboolean
___lambda7__webkit_download_decide_destination (WebKitDownload* _sender,
                                                const gchar* suggested_filename,
                                                gpointer self)
{
	gboolean result;
	result = __lambda7_ (self, suggested_filename);
	return result;
}

static void
__lambda5_ (App* self,
            WebKitDownload* download)
{
	Block3Data* _data3_;
	WebKitDownload* _tmp0_;
	g_return_if_fail (download != NULL);
	_data3_ = g_slice_new0 (Block3Data);
	_data3_->_ref_count_ = 1;
	_data3_->self = g_object_ref (self);
	_tmp0_ = _g_object_ref0 (download);
	_g_object_unref0 (_data3_->download);
	_data3_->download = _tmp0_;
	g_signal_connect_data (_data3_->download, "finished", (GCallback) ___lambda6__webkit_download_finished, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
	g_signal_connect_data (_data3_->download, "decide-destination", (GCallback) ___lambda7__webkit_download_decide_destination, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
	block3_data_unref (_data3_);
	_data3_ = NULL;
}

static void
___lambda5__webkit_network_session_download_started (WebKitNetworkSession* _sender,
                                                     WebKitDownload* download,
                                                     gpointer self)
{
	__lambda5_ ((App*) self, download);
}

static gboolean
__lambda8_ (App* self)
{
	GtkApplication* _tmp0_;
	gboolean result;
	_tmp0_ = self->app;
	g_application_quit ((GApplication*) _tmp0_);
	result = TRUE;
	return result;
}

static gboolean
___lambda8__gtk_window_close_request (GtkWindow* _sender,
                                      gpointer self)
{
	gboolean result;
	result = __lambda8_ ((App*) self);
	return result;
}

static gboolean
__lambda9_ (Block2Data* _data2_,
            WebKitLoadEvent e)
{
	App* self;
	WebKitWebView* _tmp0_;
	gboolean result;
	self = _data2_->self;
	_tmp0_ = self->webview;
	webkit_web_view_load_uri (_tmp0_, _data2_->uri);
	result = TRUE;
	return result;
}

static gboolean
___lambda9__webkit_web_view_load_failed (WebKitWebView* _sender,
                                         WebKitLoadEvent load_event,
                                         const gchar* failing_uri,
                                         GError* _error_,
                                         gpointer self)
{
	gboolean result;
	result = __lambda9_ (self, load_event);
	return result;
}

static gboolean
__lambda10_ (App* self,
             WebKitContextMenu* menu)
{
	gboolean result;
	g_return_val_if_fail (menu != NULL, FALSE);
	app_modify_menu (self, menu);
	result = FALSE;
	return result;
}

static gboolean
___lambda10__webkit_web_view_context_menu (WebKitWebView* _sender,
                                           WebKitContextMenu* context_menu,
                                           WebKitHitTestResult* hit_test_result,
                                           gpointer self)
{
	gboolean result;
	result = __lambda10_ ((App*) self, context_menu);
	return result;
}

static void
app_on_app_activate (App* self,
                     GtkApplication* app,
                     const gchar* uri)
{
	Block2Data* _data2_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	GtkWindow* win = NULL;
	GtkWindow* _tmp2_;
	const gchar* _tmp3_;
	GtkApplication* _tmp4_;
	WebKitWebView* _tmp5_;
	WebKitWebView* _tmp6_;
	WebKitSettings* settings = NULL;
	WebKitWebView* _tmp7_;
	WebKitSettings* _tmp8_;
	WebKitSettings* _tmp9_;
	WebKitWebView* _tmp10_;
	WebKitWebView* _tmp11_;
	WebKitNetworkSession* _tmp12_;
	WebKitNetworkSession* _tmp13_;
	WebKitWebView* _tmp14_;
	WebKitWebView* _tmp15_;
	WebKitWebView* _tmp16_;
	GtkWindow* _tmp17_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (app != NULL);
	g_return_if_fail (uri != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_tmp0_ = g_strdup (uri);
	_g_free0 (_data2_->uri);
	_data2_->uri = _tmp0_;
	_tmp1_ = g_strdup (_data2_->uri);
	_g_free0 (self->priv->home_url);
	self->priv->home_url = _tmp1_;
	_tmp2_ = (GtkWindow*) gtk_window_new ();
	g_object_ref_sink (_tmp2_);
	win = _tmp2_;
	_tmp3_ = self->priv->title;
	gtk_window_set_title (win, _tmp3_);
	_tmp4_ = self->app;
	gtk_application_add_window (_tmp4_, win);
	_tmp5_ = (WebKitWebView*) webkit_web_view_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->webview);
	self->webview = _tmp5_;
	_tmp6_ = self->webview;
	gtk_window_set_child (win, (GtkWidget*) _tmp6_);
	_tmp7_ = self->webview;
	_tmp8_ = webkit_web_view_get_settings (_tmp7_);
	_tmp9_ = _g_object_ref0 (_tmp8_);
	settings = _tmp9_;
	webkit_settings_set_allow_file_access_from_file_urls (settings, TRUE);
	webkit_settings_set_allow_modal_dialogs (settings, TRUE);
	webkit_settings_set_allow_top_navigation_to_data_urls (settings, TRUE);
	webkit_settings_set_allow_universal_access_from_file_urls (settings, TRUE);
	webkit_settings_set_enable_webgl (settings, TRUE);
	webkit_settings_set_enable_webrtc (settings, TRUE);
	webkit_settings_set_enable_html5_database (settings, TRUE);
	webkit_settings_set_enable_html5_local_storage (settings, TRUE);
	webkit_settings_set_enable_encrypted_media (settings, TRUE);
	webkit_settings_set_enable_media (settings, TRUE);
	webkit_settings_set_enable_media_capabilities (settings, TRUE);
	webkit_settings_set_enable_media_stream (settings, TRUE);
	webkit_settings_set_enable_mediasource (settings, TRUE);
	webkit_settings_set_enable_write_console_messages_to_stdout (settings, TRUE);
	webkit_settings_set_user_agent (settings, "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Geck" \
"o) Version/60.5 Safari/605.1.15 Chrome/120.0.0.0 Safari/537.36");
	webkit_settings_set_javascript_can_open_windows_automatically (settings, TRUE);
	webkit_settings_set_javascript_can_access_clipboard (settings, TRUE);
	webkit_settings_set_auto_load_images (settings, TRUE);
	webkit_settings_set_enable_javascript (settings, TRUE);
	webkit_settings_set_enable_javascript_markup (settings, TRUE);
	webkit_settings_set_enable_tabs_to_links (settings, TRUE);
	_tmp10_ = self->webview;
	gtk_widget_set_child_visible ((GtkWidget*) _tmp10_, TRUE);
	_tmp11_ = self->webview;
	_tmp12_ = webkit_web_view_get_network_session (_tmp11_);
	_tmp13_ = _tmp12_;
	g_signal_connect_object (_tmp13_, "download-started", (GCallback) ___lambda5__webkit_network_session_download_started, self, 0);
	g_signal_connect_object (win, "close-request", (GCallback) ___lambda8__gtk_window_close_request, self, 0);
	_tmp14_ = self->webview;
	g_signal_connect_data (_tmp14_, "load-failed", (GCallback) ___lambda9__webkit_web_view_load_failed, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	_tmp15_ = self->webview;
	webkit_web_view_load_uri (_tmp15_, _data2_->uri);
	_tmp16_ = self->webview;
	g_signal_connect_object (_tmp16_, "context-menu", (GCallback) ___lambda10__webkit_web_view_context_menu, self, 0);
	g_object_set ((GObject*) settings, "enable-developer_extras", TRUE, NULL, NULL);
	gtk_window_present (win);
	_tmp17_ = _g_object_ref0 (win);
	_g_object_unref0 (self->win);
	self->win = _tmp17_;
	_g_object_unref0 (settings);
	_g_object_unref0 (win);
	block2_data_unref (_data2_);
	_data2_ = NULL;
}

static void
__lambda11_ (App* self)
{
	WebKitWebView* _tmp0_;
	const gchar* _tmp1_;
	_tmp0_ = self->webview;
	_tmp1_ = self->priv->home_url;
	webkit_web_view_load_uri (_tmp0_, _tmp1_);
}

static void
___lambda11__g_simple_action_activate (GSimpleAction* _sender,
                                       GVariant* parameter,
                                       gpointer self)
{
	__lambda11_ ((App*) self);
}

static void
app_modify_menu (App* self,
                 WebKitContextMenu* menu)
{
	GSimpleAction* act1 = NULL;
	GSimpleAction* _tmp0_;
	WebKitContextMenuItem* item = NULL;
	WebKitContextMenuItem* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (menu != NULL);
	_tmp0_ = g_simple_action_new ("go home", NULL);
	act1 = _tmp0_;
	g_signal_connect_object (act1, "activate", (GCallback) ___lambda11__g_simple_action_activate, self, 0);
	_tmp1_ = webkit_context_menu_item_new_from_gaction (G_TYPE_CHECK_INSTANCE_TYPE (act1, g_action_get_type ()) ? ((GAction*) act1) : NULL, "go home", NULL);
	g_object_ref_sink (_tmp1_);
	item = _tmp1_;
	webkit_context_menu_append (menu, item);
	_g_object_unref0 (item);
	_g_object_unref0 (act1);
}

void
app_create_app (const gchar* id,
                const gchar* title,
                const gchar* url)
{
	App* _tmp0_;
	App* _tmp1_;
	g_return_if_fail (id != NULL);
	g_return_if_fail (title != NULL);
	g_return_if_fail (url != NULL);
	_tmp0_ = app_new ();
	_g_object_unref0 (app_application);
	app_application = _tmp0_;
	_tmp1_ = app_application;
	app_create (_tmp1_, id, title, url);
}

gint
app_run_app (void)
{
	App* _tmp0_;
	gint result;
	_tmp0_ = app_application;
	result = app_run (_tmp0_);
	return result;
}

void
app_quit (void)
{
	App* _tmp0_;
	GtkApplication* _tmp1_;
	_tmp0_ = app_application;
	_tmp1_ = _tmp0_->app;
	g_application_quit ((GApplication*) _tmp1_);
}

GtkApplication*
app_get_application (void)
{
	App* _tmp0_;
	GtkApplication* _tmp1_;
	GtkApplication* _tmp2_;
	GtkApplication* result;
	_tmp0_ = app_application;
	_tmp1_ = _tmp0_->app;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}

GtkWindow*
app_get_window (void)
{
	App* _tmp0_;
	GtkWindow* _tmp1_;
	GtkWindow* _tmp2_;
	GtkWindow* result;
	_tmp0_ = app_application;
	_tmp1_ = _tmp0_->win;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}

WebKitWebView*
app_get_webview (void)
{
	App* _tmp0_;
	WebKitWebView* _tmp1_;
	WebKitWebView* _tmp2_;
	WebKitWebView* result;
	_tmp0_ = app_application;
	_tmp1_ = _tmp0_->webview;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}

static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
	g_atomic_int_inc (&_data4_->_ref_count_);
	return _data4_;
}

static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
		g_slice_free (Block4Data, _data4_);
	}
}

static gboolean
__lambda12_ (Block4Data* _data4_)
{
	App* _tmp0_;
	GtkWindow* _tmp1_;
	gboolean result;
	_tmp0_ = app_application;
	_tmp1_ = _tmp0_->win;
	gtk_widget_set_size_request ((GtkWidget*) _tmp1_, _data4_->w, _data4_->h);
	result = FALSE;
	return result;
}

static gboolean
___lambda12__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda12_ (self);
	return result;
}

void
app_resize (gint w,
            gint h)
{
	Block4Data* _data4_;
	_data4_ = g_slice_new0 (Block4Data);
	_data4_->_ref_count_ = 1;
	_data4_->w = w;
	_data4_->h = h;
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda12__gsource_func, block4_data_ref (_data4_), block4_data_unref);
	block4_data_unref (_data4_);
	_data4_ = NULL;
}

static Block5Data*
block5_data_ref (Block5Data* _data5_)
{
	g_atomic_int_inc (&_data5_->_ref_count_);
	return _data5_;
}

static void
block5_data_unref (void * _userdata_)
{
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
		_g_object_unref0 (_data5_->inspector);
		g_slice_free (Block5Data, _data5_);
	}
}

static void
__lambda14_ (Block5Data* _data5_)
{
	webkit_web_inspector_close (_data5_->inspector);
}

static void
___lambda14__webkit_web_inspector_closed (WebKitWebInspector* _sender,
                                          gpointer self)
{
	__lambda14_ (self);
}

static gboolean
__lambda13_ (void)
{
	Block5Data* _data5_;
	App* _tmp0_;
	WebKitWebView* _tmp1_;
	WebKitWebInspector* _tmp2_;
	WebKitWebInspector* _tmp3_;
	gboolean result;
	_data5_ = g_slice_new0 (Block5Data);
	_data5_->_ref_count_ = 1;
	_tmp0_ = app_application;
	_tmp1_ = _tmp0_->webview;
	_tmp2_ = webkit_web_view_get_inspector (_tmp1_);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_data5_->inspector = _tmp3_;
	g_signal_connect_data (_data5_->inspector, "closed", (GCallback) ___lambda14__webkit_web_inspector_closed, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	webkit_web_inspector_show (_data5_->inspector);
	result = FALSE;
	block5_data_unref (_data5_);
	_data5_ = NULL;
	return result;
}

static gboolean
___lambda13__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda13_ ();
	return result;
}

void
app_show_inspector (void)
{
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda13__gsource_func, NULL, NULL);
}

App*
app_construct (GType object_type)
{
	App * self = NULL;
	self = (App*) g_object_new (object_type, NULL);
	return self;
}

App*
app_new (void)
{
	return app_construct (TYPE_APP);
}

static void
app_class_init (AppClass * klass,
                gpointer klass_data)
{
	app_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &App_private_offset);
	G_OBJECT_CLASS (klass)->finalize = app_finalize;
}

static void
app_instance_init (App * self,
                   gpointer klass)
{
	self->priv = app_get_instance_private (self);
	self->priv->notice_n = 0;
}

static void
app_finalize (GObject * obj)
{
	App * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_APP, App);
	_g_object_unref0 (self->app);
	_g_object_unref0 (self->webview);
	_g_object_unref0 (self->win);
	_g_free0 (self->priv->home_url);
	_g_free0 (self->priv->title);
	G_OBJECT_CLASS (app_parent_class)->finalize (obj);
}

static GType
app_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (App), 0, (GInstanceInitFunc) app_instance_init, NULL };
	GType app_type_id;
	app_type_id = g_type_register_static (G_TYPE_OBJECT, "App", &g_define_type_info, 0);
	App_private_offset = g_type_add_instance_private (app_type_id, sizeof (AppPrivate));
	return app_type_id;
}

GType
app_get_type (void)
{
	static volatile gsize app_type_id__once = 0;
	if (g_once_init_enter (&app_type_id__once)) {
		GType app_type_id;
		app_type_id = app_get_type_once ();
		g_once_init_leave (&app_type_id__once, app_type_id);
	}
	return app_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

